name: chromeapi
description: Chrome Extension API wrapper
version: 0.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  js: ^0.6.5
